{"timestamp": "2025-08-18T11:57:11.321576", "type": "error", "component": "sensor", "error_message": "No temperature data available for local API request"}
{"timestamp": "2025-08-18T11:57:53.122655", "type": "error", "component": "sensor", "error_message": "No temperature data available for local API request"}
{"timestamp": "2025-08-18T11:57:54.647524", "type": "error", "component": "sensor", "error_message": "No temperature data available for local API request"}
{"timestamp": "2025-08-19T10:26:46.298266", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023BE2961950>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))"}
{"timestamp": "2025-08-19T10:27:01.353789", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE2961BD0>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T10:27:16.361172", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE29607D0>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T10:27:31.367827", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE2961A90>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T10:27:56.737842", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE2961E50>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T10:28:11.752536", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE2962210>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
